# Docker Compose setup for testing kit tools
# This demonstrates various service types that kit tools can manage

version: '3.8'

services:
  # Database services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - database
      - dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    profiles:
      - cache
      - database
      - dev

  # Application services
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://testuser:test123@postgres:5432/testdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    profiles:
      - app
      - dev

  # Development tools
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    profiles:
      - proxy
      - dev

  # Testing service
  test-runner:
    build: .
    command: ["echo", "Running tests..."]
    environment:
      - NODE_ENV=test
    depends_on:
      - postgres
      - redis
    profiles:
      - test

volumes:
  postgres_data:
  redis_data: