# ast-grep configuration for oc-kit project
ruleDirs:
  - .

# Global file exclusions
ignore:
  - "examples/**"
  - "node_modules/**"
  - "dist/**"
  - ".git/**"
  - "*.d.ts"

# Rule configuration file
ruleFile: oc-kit-rules.yml